/* automatically generated from xfwm4-tweaks-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (tweaks_dialog_ui)
#endif
#ifdef __GNUC__
static const char tweaks_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char tweaks_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><object class=\"Gt"
  "kAdjustment\" id=\"adjustment1\"><property name=\"upper\">100</property"
  "><property name=\"value\">75</property><property name=\"step_increment\""
  ">1</property><property name=\"page_increment\">10</property></object><o"
  "bject class=\"GtkAdjustment\" id=\"adjustment2\"><property name=\"upper"
  "\">100</property><property name=\"value\">90</property><property name=\""
  "step_increment\">1</property><property name=\"page_increment\">10</prop"
  "erty></object><object class=\"GtkAdjustment\" id=\"adjustment3\"><prope"
  "rty name=\"upper\">100</property><property name=\"value\">90</property>"
  "<property name=\"step_increment\">1</property><property name=\"page_inc"
  "rement\">10</property></object><object class=\"GtkAdjustment\" id=\"adj"
  "ustment4\"><property name=\"upper\">100</property><property name=\"valu"
  "e\">90</property><property name=\"step_increment\">1</property><propert"
  "y name=\"page_increment\">10</property></object><object class=\"GtkAdju"
  "stment\" id=\"adjustment5\"><property name=\"upper\">100</property><pro"
  "perty name=\"value\">90</property><property name=\"step_increment\">1</"
  "property><property name=\"page_increment\">10</property></object><objec"
  "t class=\"GtkAdjustment\" id=\"adjustment6\"><property name=\"upper\">1"
  "00</property><property name=\"value\">90</property><property name=\"ste"
  "p_increment\">1</property><property name=\"page_increment\">10</propert"
  "y></object><object class=\"XfceTitledDialog\" id=\"main-dialog\"><prope"
  "rty name=\"can_focus\">False</property><property name=\"title\" transla"
  "table=\"yes\">Window Manager Tweaks</property><property name=\"window_p"
  "osition\">center-on-parent</property><property name=\"default_height\">"
  "480</property><property name=\"icon_name\">wmtweaks</property><property"
  " name=\"type_hint\">dialog</property><property name=\"subtitle\" transl"
  "atable=\"yes\">Fine-tune window behaviour and effects</property><child "
  "internal-child=\"vbox\"><object class=\"GtkVBox\" id=\"main-vbox\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><child internal-child=\"action_area\"><object class=\"GtkHB"
  "uttonBox\" id=\"dialog-action_area1\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "layout_style\">end</property><child><object class=\"GtkButton\" id=\"bu"
  "tton2\"><property name=\"label\">gtk-help</property><property name=\"us"
  "e_action_appearance\">False</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">True</property><property name=\"use_stock\">True</pro"
  "perty></object><packing><property name=\"expand\">False</property><prop"
  "erty name=\"fill\">False</property><property name=\"position\">0</prope"
  "rty><property name=\"secondary\">True</property></packing></child><chil"
  "d><object class=\"GtkButton\" id=\"button1\"><property name=\"label\">g"
  "tk-close</property><property name=\"use_action_appearance\">False</prop"
  "erty><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"receives_default\">True</property>"
  "<property name=\"use_stock\">True</property></object><packing><property"
  " name=\"expand\">False</property><property name=\"fill\">False</propert"
  "y><property name=\"position\">1</property></packing></child></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">True</property><property name=\"pack_type\">end</property><property na"
  "me=\"position\">0</property></packing></child><child><object class=\"Gt"
  "kNotebook\" id=\"plug-child\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"border_wi"
  "dth\">6</property><child><object class=\"GtkVBox\" id=\"vbox1\"><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">False</"
  "property><property name=\"border_width\">12</property><property name=\""
  "spacing\">6</property><child><object class=\"GtkCheckButton\" id=\"cycl"
  "e_minimum_check\"><property name=\"label\" translatable=\"yes\">S_kip w"
  "indows that have \"skip pager\"\nor \"skip taskbar\" properties set</pr"
  "operty><property name=\"use_action_appearance\">False</property><proper"
  "ty name=\"visible\">True</property><property name=\"can_focus\">True</p"
  "roperty><property name=\"receives_default\">False</property><property n"
  "ame=\"use_underline\">True</property><property name=\"draw_indicator\">"
  "True</property></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">False</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkCheckButton\" "
  "id=\"cycle_hidden_check\"><property name=\"label\" translatable=\"yes\""
  ">_Include hidden (i.e. iconified) windows</property><property name=\"us"
  "e_action_appearance\">False</property><property name=\"visible\">True</"
  "property><property name=\"can_focus\">True</property><property name=\"r"
  "eceives_default\">False</property><property name=\"use_underline\">True"
  "</property><property name=\"draw_indicator\">True</property></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">1</property></packing></ch"
  "ild><child><object class=\"GtkCheckButton\" id=\"cycle_workspaces_check"
  "\"><property name=\"label\" translatable=\"yes\">Cycle _through windows"
  " on all workspaces</property><property name=\"use_action_appearance\">F"
  "alse</property><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"receives_default\">False"
  "</property><property name=\"use_underline\">True</property><property na"
  "me=\"draw_indicator\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">2</property></packing></child><child><object clas"
  "s=\"GtkCheckButton\" id=\"cycle_draw_frame\"><property name=\"label\" t"
  "ranslatable=\"yes\">_Draw frame around selected windows while cycling</"
  "property><property name=\"use_action_appearance\">False</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"receives_default\">False</property><property"
  " name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">3</property></packing></child><child><object class=\"GtkCheckButton\" "
  "id=\"cycle_tabwin_mode\"><property name=\"label\" translatable=\"yes\">"
  "Cycle through windows in a _list</property><property name=\"use_action_"
  "appearance\">False</property><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">True</property><property name=\"receives_d"
  "efault\">False</property><property name=\"use_underline\">True</propert"
  "y><property name=\"draw_indicator\">True</property></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">False</"
  "property><property name=\"position\">4</property></packing></child></ob"
  "ject></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"label1"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"label\" translatable=\"yes\">C_ycli"
  "ng</property><property name=\"use_underline\">True</property></object><"
  "packing><property name=\"tab_fill\">False</property></packing></child><"
  "child><object class=\"GtkVBox\" id=\"vbox3\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"border_width\">12</property><property name=\"spacing\">6</proper"
  "ty><child><object class=\"GtkCheckButton\" id=\"prevent_focus_stealing_"
  "check\"><property name=\"label\" translatable=\"yes\">Activate foc_us s"
  "tealing prevention</property><property name=\"use_action_appearance\">F"
  "alse</property><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"receives_default\">False"
  "</property><property name=\"use_underline\">True</property><property na"
  "me=\"draw_indicator\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">0</property></packing></child><child><object clas"
  "s=\"GtkCheckButton\" id=\"focus_hint_check\"><property name=\"label\" t"
  "ranslatable=\"yes\">Honor _standard ICCCM focus hint</property><propert"
  "y name=\"use_action_appearance\">False</property><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">True</property><proper"
  "ty name=\"receives_default\">False</property><property name=\"use_under"
  "line\">True</property><property name=\"draw_indicator\">True</property>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">False</property><property name=\"position\">1</property></"
  "packing></child><child><object class=\"GtkVBox\" id=\"prevent_focus_ste"
  "aling_box\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"spacing\">6</property><chi"
  "ld><object class=\"GtkLabel\" id=\"label11\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"xalign\">0</property><property name=\"label\" translatable=\"yes"
  "\">When a window raises itself:</property></object><packing><property n"
  "ame=\"expand\">True</property><property name=\"fill\">True</property><p"
  "roperty name=\"position\">0</property></packing></child><child><object "
  "class=\"GtkAlignment\" id=\"alignment2\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"bottom_padding\">6</property><property name=\"left_padding\">12</pro"
  "perty><child><object class=\"GtkVBox\" id=\"vbox14\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"border_width\">6</property><property name=\"spacing\">6<"
  "/property><child><object class=\"GtkRadioButton\" id=\"activate_action_"
  "bring_option\"><property name=\"label\" translatable=\"yes\">_Bring win"
  "dow on current workspace</property><property name=\"use_action_appearan"
  "ce\">False</property><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">True</property><property name=\"receives_default\""
  ">False</property><property name=\"use_underline\">True</property><prope"
  "rty name=\"active\">True</property><property name=\"draw_indicator\">Tr"
  "ue</property></object><packing><property name=\"expand\">True</property"
  "><property name=\"fill\">True</property><property name=\"position\">0</"
  "property></packing></child><child><object class=\"GtkRadioButton\" id=\""
  "activate_action_switch_option\"><property name=\"label\" translatable=\""
  "yes\">Switch to win_dow\'s workspace</property><property name=\"use_act"
  "ion_appearance\">False</property><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">True</property><property name=\"receiv"
  "es_default\">False</property><property name=\"use_underline\">True</pro"
  "perty><property name=\"active\">True</property><property name=\"draw_in"
  "dicator\">True</property><property name=\"group\">activate_action_bring"
  "_option</property></object><packing><property name=\"expand\">True</pro"
  "perty><property name=\"fill\">True</property><property name=\"position\""
  ">1</property></packing></child><child><object class=\"GtkRadioButton\" "
  "id=\"activate_action_none_option\"><property name=\"label\" translatabl"
  "e=\"yes\">Do _nothing</property><property name=\"use_action_appearance\""
  ">False</property><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">True</property><property name=\"receives_default\">Fal"
  "se</property><property name=\"use_underline\">True</property><property "
  "name=\"active\">True</property><property name=\"draw_indicator\">True</"
  "property><property name=\"group\">activate_action_bring_option</propert"
  "y></object><packing><property name=\"expand\">True</property><property "
  "name=\"fill\">True</property><property name=\"position\">2</property></"
  "packing></child></object></child></object><packing><property name=\"exp"
  "and\">True</property><property name=\"fill\">True</property><property n"
  "ame=\"position\">1</property></packing></child></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">False</prop"
  "erty><property name=\"position\">2</property></packing></child></object"
  "><packing><property name=\"position\">1</property></packing></child><ch"
  "ild type=\"tab\"><object class=\"GtkLabel\" id=\"label2\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"label\" translatable=\"yes\">_Focus</property><prop"
  "erty name=\"use_underline\">True</property></object><packing><property "
  "name=\"position\">1</property><property name=\"tab_fill\">False</proper"
  "ty></packing></child><child><object class=\"GtkVBox\" id=\"vbox4\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"border_width\">12</property><property name"
  "=\"spacing\">6</property><child><object class=\"GtkHBox\" id=\"hbox1\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"spacing\">12</property><child><object "
  "class=\"GtkLabel\" id=\"label7\"><property name=\"visible\">True</prope"
  "rty><property name=\"can_focus\">False</property><property name=\"xalig"
  "n\">0</property><property name=\"label\" translatable=\"yes\">Key used "
  "to _grab and move windows:</property><property name=\"use_underline\">T"
  "rue</property><property name=\"mnemonic_widget\">easy_click_combo_box</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">False</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkComboBox\" id=\"easy"
  "_click_combo_box\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"fill\">False</property><proper"
  "ty name=\"position\">1</property></packing></child></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">False</"
  "property><property name=\"position\">0</property></packing></child><chi"
  "ld><object class=\"GtkCheckButton\" id=\"raise_with_any_button_check\">"
  "<property name=\"label\" translatable=\"yes\">_Raise windows when any m"
  "ouse button is pressed</property><property name=\"use_action_appearance"
  "\">False</property><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"receives_default\">F"
  "alse</property><property name=\"use_underline\">True</property><propert"
  "y name=\"draw_indicator\">True</property></object><packing><property na"
  "me=\"expand\">False</property><property name=\"fill\">False</property><"
  "property name=\"position\">1</property></packing></child><child><object"
  " class=\"GtkCheckButton\" id=\"borderless_maximize_check\"><property na"
  "me=\"label\" translatable=\"yes\">Hide frame of windows when ma_ximized"
  "</property><property name=\"use_action_appearance\">False</property><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Tru"
  "e</property><property name=\"receives_default\">False</property><proper"
  "ty name=\"use_underline\">True</property><property name=\"draw_indicato"
  "r\">True</property></object><packing><property name=\"expand\">False</p"
  "roperty><property name=\"fill\">False</property><property name=\"positi"
  "on\">2</property></packing></child><child><object class=\"GtkCheckButto"
  "n\" id=\"titleless_maximize_check\"><property name=\"label\" translatab"
  "le=\"yes\">Hide title of windows when maximized</property><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">True</propert"
  "y><property name=\"receives_default\">False</property><property name=\""
  "use_underline\">True</property><property name=\"draw_indicator\">True</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">False</property><property name=\"position\">3</pr"
  "operty></packing></child><child><object class=\"GtkCheckButton\" id=\"t"
  "ile_on_move_check\"><property name=\"label\" translatable=\"yes\">Autom"
  "atically _tile windows when moving toward the screen edge</property><pr"
  "operty name=\"use_action_appearance\">False</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">False</property><property name=\"use_"
  "underline\">True</property><property name=\"draw_indicator\">True</prop"
  "erty></object><packing><property name=\"expand\">False</property><prope"
  "rty name=\"fill\">False</property><property name=\"position\">4</proper"
  "ty></packing></child><child><object class=\"GtkCheckButton\" id=\"snap_"
  "resist_check\"><property name=\"label\" translatable=\"yes\">Use _edge "
  "resistance instead of window snapping</property><property name=\"use_ac"
  "tion_appearance\">False</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">False</property><property name=\"use_underline\">True</pr"
  "operty><property name=\"draw_indicator\">True</property></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Fa"
  "lse</property><property name=\"position\">5</property></packing></child"
  "><child><object class=\"GtkCheckButton\" id=\"urgent_blink\"><property "
  "name=\"label\" translatable=\"yes\">Notify of _urgency by making window"
  "\'s decoration blink</property><property name=\"use_action_appearance\""
  ">False</property><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">True</property><property name=\"receives_default\">Fal"
  "se</property><property name=\"use_underline\">True</property><property "
  "name=\"draw_indicator\">True</property></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">False</property><pr"
  "operty name=\"position\">6</property></packing></child><child><object c"
  "lass=\"GtkCheckButton\" id=\"repeat_urgent_blink\"><property name=\"lab"
  "el\" translatable=\"yes\">Keep urgent windows _blinking repeatedly</pro"
  "perty><property name=\"use_action_appearance\">False</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"receives_default\">False</property><property na"
  "me=\"use_underline\">True</property><property name=\"draw_indicator\">T"
  "rue</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "7</property></packing></child><child><object class=\"GtkCheckButton\" i"
  "d=\"mousewheel_rollup\"><property name=\"label\" translatable=\"yes\">U"
  "se mouse wheel on title bar to ro_ll up the window</property><property "
  "name=\"use_action_appearance\">False</property><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><property"
  " name=\"receives_default\">False</property><property name=\"use_underli"
  "ne\">True</property><property name=\"draw_indicator\">True</property></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">False</property><property name=\"position\">7</property></pa"
  "cking></child></object><packing><property name=\"position\">2</property"
  "></packing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\""
  "label3\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\">"
  "_Accessibility</property><property name=\"use_underline\">True</propert"
  "y></object><packing><property name=\"position\">2</property><property n"
  "ame=\"tab_fill\">False</property></packing></child><child><object class"
  "=\"GtkVBox\" id=\"vbox5\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"border_width"
  "\">12</property><property name=\"spacing\">6</property><child><object c"
  "lass=\"GtkCheckButton\" id=\"scroll_workspaces_check\"><property name=\""
  "label\" translatable=\"yes\">Use the _mouse wheel on the desktop to swi"
  "tch workspaces</property><property name=\"use_action_appearance\">False"
  "</property><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">True</property><property name=\"receives_default\">False</pr"
  "operty><property name=\"use_underline\">True</property><property name=\""
  "draw_indicator\">True</property></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">False</property><property "
  "name=\"position\">0</property></packing></child><child><object class=\""
  "GtkCheckButton\" id=\"toggle_workspaces_check\"><property name=\"label\""
  " translatable=\"yes\">_Remember and recall previous workspace\nwhen swi"
  "tching via keyboard shortcuts</property><property name=\"use_action_app"
  "earance\">False</property><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">True</property><property name=\"receives_defa"
  "ult\">False</property><property name=\"use_underline\">True</property><"
  "property name=\"draw_indicator\">True</property></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">False</pro"
  "perty><property name=\"position\">1</property></packing></child><child>"
  "<object class=\"GtkCheckButton\" id=\"wrap_layout_check\"><property nam"
  "e=\"label\" translatable=\"yes\">Wrap workspaces depending on the actua"
  "l desktop _layout</property><property name=\"use_action_appearance\">Fa"
  "lse</property><property name=\"visible\">True</property><property name="
  "\"can_focus\">True</property><property name=\"receives_default\">False<"
  "/property><property name=\"use_underline\">True</property><property nam"
  "e=\"draw_indicator\">True</property></object><packing><property name=\""
  "expand\">False</property><property name=\"fill\">False</property><prope"
  "rty name=\"position\">2</property></packing></child><child><object clas"
  "s=\"GtkCheckButton\" id=\"wrap_cycle_check\"><property name=\"label\" t"
  "ranslatable=\"yes\">Wrap workspaces when _the first or the last workspa"
  "ce is reached</property><property name=\"use_action_appearance\">False<"
  "/property><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">True</property><property name=\"receives_default\">False</pro"
  "perty><property name=\"use_underline\">True</property><property name=\""
  "draw_indicator\">True</property></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">False</property><property "
  "name=\"position\">3</property></packing></child></object><packing><prop"
  "erty name=\"position\">3</property></packing></child><child type=\"tab\""
  "><object class=\"GtkLabel\" id=\"label4\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"label\" translatable=\"yes\">_Workspaces</property><property name=\""
  "use_underline\">True</property></object><packing><property name=\"posit"
  "ion\">3</property><property name=\"tab_fill\">False</property></packing"
  "></child><child><object class=\"GtkVBox\" id=\"vbox6\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"border_width\">12</property><property name=\"spacing\">"
  "6</property><child><object class=\"GtkLabel\" id=\"label8\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"xalign\">0</property><property name=\"label\" tra"
  "nslatable=\"yes\">_Minimum size of windows to trigger smart placement:<"
  "/property><property name=\"use_underline\">True</property><property nam"
  "e=\"mnemonic_widget\">placement_ratio_scale</property></object><packing"
  "><property name=\"expand\">False</property><property name=\"fill\">Fals"
  "e</property><property name=\"position\">0</property></packing></child><"
  "child><object class=\"GtkAlignment\" id=\"alignment4\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"bottom_padding\">6</property><property name=\"left_padd"
  "ing\">12</property><child><object class=\"GtkHBox\" id=\"hbox2\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"spacing\">12</property><child><object class="
  "\"GtkLabel\" id=\"label9\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"label\" tra"
  "nslatable=\"yes\" comments=\"Smart placement size\">&lt;i&gt;Small&lt;/"
  "i&gt;</property><property name=\"use_markup\">True</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">False</property><property name=\"position\">0</property></packing></"
  "child><child><object class=\"GtkHScale\" id=\"placement_ratio_scale\"><"
  "property name=\"visible\">True</property><property name=\"can_focus\">T"
  "rue</property><property name=\"adjustment\">adjustment1</property><prop"
  "erty name=\"restrict_to_fill_level\">False</property><property name=\"d"
  "raw_value\">False</property></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child><child><object class=\"GtkLabe"
  "l\" id=\"label10\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><property name=\"label\" translatabl"
  "e=\"yes\" comments=\"Smart placement size\">&lt;i&gt;Large&lt;/i&gt;</p"
  "roperty><property name=\"use_markup\">True</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">True<"
  "/property><property name=\"position\">2</property></packing></child></o"
  "bject></child></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "1</property></packing></child><child><object class=\"GtkVBox\" id=\"def"
  "ault_placement_box\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"spacing\">6</prop"
  "erty><child><object class=\"GtkLabel\" id=\"label27\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"xalign\">0</property><property name=\"label\" translata"
  "ble=\"yes\">By default, place windows:</property></object><packing><pro"
  "perty name=\"expand\">True</property><property name=\"fill\">True</prop"
  "erty><property name=\"position\">0</property></packing></child><child><"
  "object class=\"GtkAlignment\" id=\"alignment10\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"bottom_padding\">6</property><property name=\"left_padding\""
  ">12</property><child><object class=\"GtkVBox\" id=\"vbox18\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"border_width\">6</property><property name=\"spac"
  "ing\">6</property><child><object class=\"GtkRadioButton\" id=\"placemen"
  "t_center_option\"><property name=\"label\" translatable=\"yes\">At the "
  "c_enter of the screen</property><property name=\"use_action_appearance\""
  ">False</property><property name=\"visible\">True</property><property na"
  "me=\"can_focus\">True</property><property name=\"receives_default\">Fal"
  "se</property><property name=\"use_underline\">True</property><property "
  "name=\"draw_indicator\">True</property></object><packing><property name"
  "=\"expand\">True</property><property name=\"fill\">True</property><prop"
  "erty name=\"position\">0</property></packing></child><child><object cla"
  "ss=\"GtkRadioButton\" id=\"placement_mouse_option\"><property name=\"la"
  "bel\" translatable=\"yes\">U_nder the mouse pointer</property><property"
  " name=\"use_action_appearance\">False</property><property name=\"visibl"
  "e\">True</property><property name=\"can_focus\">True</property><propert"
  "y name=\"receives_default\">False</property><property name=\"use_underl"
  "ine\">True</property><property name=\"active\">True</property><property"
  " name=\"draw_indicator\">True</property><property name=\"group\">placem"
  "ent_center_option</property></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child></object></child></object><pac"
  "king><property name=\"expand\">True</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">1</property></packing></child"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">False</property><property name=\"position\">2</property><"
  "/packing></child></object><packing><property name=\"position\">4</prope"
  "rty></packing></child><child type=\"tab\"><object class=\"GtkLabel\" id"
  "=\"label5\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label\" translatable=\"yes"
  "\">_Placement</property><property name=\"use_underline\">True</property"
  "></object><packing><property name=\"position\">4</property><property na"
  "me=\"tab_fill\">False</property></packing></child><child><object class="
  "\"GtkVBox\" id=\"vbox7\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"border_width\""
  ">12</property><property name=\"spacing\">6</property><child><object cla"
  "ss=\"GtkCheckButton\" id=\"use_compositing_check\"><property name=\"lab"
  "el\" translatable=\"yes\">_Enable display compositing</property><proper"
  "ty name=\"use_action_appearance\">False</property><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"receives_default\">False</property><property name=\"use_unde"
  "rline\">True</property><property name=\"draw_indicator\">True</property"
  "></object><packing><property name=\"expand\">False</property><property "
  "name=\"fill\">False</property><property name=\"position\">0</property><"
  "/packing></child><child><object class=\"GtkScrolledWindow\" id=\"use_co"
  "mpositing_box\"><property name=\"visible\">True</property><property nam"
  "e=\"sensitive\">False</property><property name=\"can_focus\">True</prop"
  "erty><property name=\"hscrollbar_policy\">never</property><property nam"
  "e=\"vscrollbar_policy\">automatic</property><child><object class=\"GtkV"
  "iewport\" id=\"viewport1\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"resize_mode"
  "\">queue</property><property name=\"shadow_type\">none</property><child"
  "><object class=\"GtkAlignment\" id=\"alignment3\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">False</property><prop"
  "erty name=\"bottom_padding\">6</property><property name=\"left_padding\""
  ">12</property><child><object class=\"GtkVBox\" id=\"vbox8\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"spacing\">6</property><child><object class=\"GtkC"
  "heckButton\" id=\"unredirect_overlays_check\"><property name=\"label\" "
  "translatable=\"yes\">Display _fullscreen overlay windows directly</prop"
  "erty><property name=\"use_action_appearance\">False</property><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"receives_default\">False</property><property nam"
  "e=\"use_underline\">True</property><property name=\"draw_indicator\">Tr"
  "ue</property></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">True</property><property name=\"position\">0<"
  "/property></packing></child><child><object class=\"GtkCheckButton\" id="
  "\"sync_to_vblank_check\"><property name=\"label\" translatable=\"yes\">"
  "Synchronize drawing to the _vertical blank</property><property name=\"u"
  "se_action_appearance\">False</property><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">False</property><property name=\"use_underline\">Tru"
  "e</property><property name=\"draw_indicator\">True</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">True</property><property name=\"position\">1</property></packing></c"
  "hild><child><object class=\"GtkCheckButton\" id=\"cycle_preview_check\""
  "><property name=\"label\" translatable=\"yes\">Show windows preview in "
  "place of icons when cycling</property><property name=\"use_action_appea"
  "rance\">False</property><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"receives_defaul"
  "t\">False</property><property name=\"use_underline\">True</property><pr"
  "operty name=\"draw_indicator\">True</property></object><packing><proper"
  "ty name=\"expand\">False</property><property name=\"fill\">True</proper"
  "ty><property name=\"position\">2</property></packing></child><child><ob"
  "ject class=\"GtkCheckButton\" id=\"show_popup_shadow_check\"><property "
  "name=\"label\" translatable=\"yes\">Show shadows under pop_up windows</"
  "property><property name=\"use_action_appearance\">False</property><prop"
  "erty name=\"visible\">True</property><property name=\"can_focus\">True<"
  "/property><property name=\"receives_default\">False</property><property"
  " name=\"use_underline\">True</property><property name=\"draw_indicator\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">True</property><property name=\"position\""
  ">3</property></packing></child><child><object class=\"GtkCheckButton\" "
  "id=\"show_dock_shadow_check\"><property name=\"label\" translatable=\"y"
  "es\">Show shadows under _dock windows</property><property name=\"use_ac"
  "tion_appearance\">False</property><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">True</property><property name=\"recei"
  "ves_default\">False</property><property name=\"use_underline\">True</pr"
  "operty><property name=\"draw_indicator\">True</property></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">4</property></packing></child>"
  "<child><object class=\"GtkCheckButton\" id=\"show_frame_shadow_check\">"
  "<property name=\"label\" translatable=\"yes\">Show shadows under _regul"
  "ar windows</property><property name=\"use_action_appearance\">False</pr"
  "operty><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">True</property><property name=\"receives_default\">False</proper"
  "ty><property name=\"use_underline\">True</property><property name=\"dra"
  "w_indicator\">True</property></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">True</property><property name="
  "\"position\">5</property></packing></child><child><object class=\"GtkLa"
  "bel\" id=\"label12\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"xalign\">0</prope"
  "rty><property name=\"label\" translatable=\"yes\">Opaci_ty of window de"
  "corations:</property><property name=\"use_underline\">True</property><p"
  "roperty name=\"mnemonic_widget\">frame_opacity_scale</property></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">True</property><property name=\"position\">6</property></packing><"
  "/child><child><object class=\"GtkAlignment\" id=\"alignment5\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"top_padding\">2</property><property name=\"lef"
  "t_padding\">12</property><child><object class=\"GtkHBox\" id=\"hbox3\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><child><object class=\"GtkLabel\" id=\"label17\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"label\" translatable=\"yes\">&lt;i&gt;Transp"
  "arent&lt;/i&gt;</property><property name=\"use_markup\">True</property>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">False</property><property name=\"position\">0</property></"
  "packing></child><child><object class=\"GtkHScale\" id=\"frame_opacity_s"
  "cale\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">True</property><property name=\"update_policy\">discontinuous</p"
  "roperty><property name=\"adjustment\">adjustment2</property><property n"
  "ame=\"restrict_to_fill_level\">False</property><property name=\"draw_va"
  "lue\">False</property></object><packing><property name=\"expand\">True<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">1</property></packing></child><child><object class=\"GtkLabel\" i"
  "d=\"label18\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"label\" translatable=\"y"
  "es\">&lt;i&gt;Opaque&lt;/i&gt;</property><property name=\"use_markup\">"
  "True</property></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">False</property><property name=\"position\""
  ">2</property></packing></child></object></child></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">False</pro"
  "perty><property name=\"position\">7</property></packing></child><child>"
  "<object class=\"GtkLabel\" id=\"label13\"><property name=\"visible\">Tr"
  "ue</property><property name=\"can_focus\">False</property><property nam"
  "e=\"xalign\">0</property><property name=\"label\" translatable=\"yes\">"
  "Opacity of _inactive windows:</property><property name=\"use_underline\""
  ">True</property><property name=\"mnemonic_widget\">inactive_opacity_sca"
  "le</property></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">False</property><property name=\"position\">8"
  "</property></packing></child><child><object class=\"GtkAlignment\" id=\""
  "alignment6\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"top_padding\">2</property>"
  "<property name=\"left_padding\">12</property><child><object class=\"Gtk"
  "HBox\" id=\"hbox4\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><child><object class=\"GtkLabel\" i"
  "d=\"label19\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"label\" translatable=\"y"
  "es\">&lt;i&gt;Transparent&lt;/i&gt;</property><property name=\"use_mark"
  "up\">True</property></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">False</property><property name=\"posit"
  "ion\">0</property></packing></child><child><object class=\"GtkHScale\" "
  "id=\"inactive_opacity_scale\"><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"update_po"
  "licy\">discontinuous</property><property name=\"adjustment\">adjustment"
  "3</property><property name=\"restrict_to_fill_level\">False</property><"
  "property name=\"draw_value\">False</property></object><packing><propert"
  "y name=\"expand\">True</property><property name=\"fill\">True</property"
  "><property name=\"position\">1</property></packing></child><child><obje"
  "ct class=\"GtkLabel\" id=\"label20\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"l"
  "abel\" translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property><proper"
  "ty name=\"use_markup\">True</property></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">False</property><pro"
  "perty name=\"position\">2</property></packing></child></object></child>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">False</property><property name=\"position\">9</property></"
  "packing></child><child><object class=\"GtkLabel\" id=\"label14\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"xalign\">0</property><property name=\"label\""
  " translatable=\"yes\">Opacity of windows during _move:</property><prope"
  "rty name=\"use_underline\">True</property><property name=\"mnemonic_wid"
  "get\">move_opacity_scale</property></object><packing><property name=\"e"
  "xpand\">False</property><property name=\"fill\">False</property><proper"
  "ty name=\"position\">10</property></packing></child><child><object clas"
  "s=\"GtkAlignment\" id=\"alignment7\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"t"
  "op_padding\">2</property><property name=\"left_padding\">12</property><"
  "child><object class=\"GtkHBox\" id=\"hbox5\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><child><ob"
  "ject class=\"GtkLabel\" id=\"label21\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "label\" translatable=\"yes\">&lt;i&gt;Transparent&lt;/i&gt;</property><"
  "property name=\"use_markup\">True</property></object><packing><property"
  " name=\"expand\">False</property><property name=\"fill\">False</propert"
  "y><property name=\"position\">0</property></packing></child><child><obj"
  "ect class=\"GtkHScale\" id=\"move_opacity_scale\"><property name=\"visi"
  "ble\">True</property><property name=\"can_focus\">True</property><prope"
  "rty name=\"update_policy\">discontinuous</property><property name=\"adj"
  "ustment\">adjustment4</property><property name=\"restrict_to_fill_level"
  "\">False</property><property name=\"draw_value\">False</property></obje"
  "ct><packing><property name=\"expand\">True</property><property name=\"f"
  "ill\">True</property><property name=\"position\">1</property></packing>"
  "</child><child><object class=\"GtkLabel\" id=\"label22\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"label\" translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&g"
  "t;</property><property name=\"use_markup\">True</property></object><pac"
  "king><property name=\"expand\">False</property><property name=\"fill\">"
  "False</property><property name=\"position\">2</property></packing></chi"
  "ld></object></child></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">False</property><property name=\"posit"
  "ion\">11</property></packing></child><child><object class=\"GtkLabel\" "
  "id=\"label15\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"xalign\">0</property><p"
  "roperty name=\"label\" translatable=\"yes\">Opacity of windows during r"
  "esi_ze:</property><property name=\"use_underline\">True</property><prop"
  "erty name=\"mnemonic_widget\">resize_opacity_scale</property></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">False</property><property name=\"position\">12</property></packing><"
  "/child><child><object class=\"GtkAlignment\" id=\"alignment8\"><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">False</p"
  "roperty><property name=\"top_padding\">2</property><property name=\"lef"
  "t_padding\">12</property><child><object class=\"GtkHBox\" id=\"hbox6\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><child><object class=\"GtkLabel\" id=\"label23\"><prope"
  "rty name=\"visible\">True</property><property name=\"can_focus\">False<"
  "/property><property name=\"label\" translatable=\"yes\">&lt;i&gt;Transp"
  "arent&lt;/i&gt;</property><property name=\"use_markup\">True</property>"
  "</object><packing><property name=\"expand\">False</property><property n"
  "ame=\"fill\">False</property><property name=\"position\">0</property></"
  "packing></child><child><object class=\"GtkHScale\" id=\"resize_opacity_"
  "scale\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">True</property><property name=\"update_policy\">discontinuous</"
  "property><property name=\"adjustment\">adjustment5</property><property "
  "name=\"restrict_to_fill_level\">False</property><property name=\"draw_v"
  "alue\">False</property></object><packing><property name=\"expand\">True"
  "</property><property name=\"fill\">True</property><property name=\"posi"
  "tion\">1</property></packing></child><child><object class=\"GtkLabel\" "
  "id=\"label24\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">&lt;i&gt;Opaque&lt;/i&gt;</property><property name=\"use_markup\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">2</property></packing></child></object></child></object><packing><prop"
  "erty name=\"expand\">False</property><property name=\"fill\">False</pro"
  "perty><property name=\"position\">13</property></packing></child><child"
  "><object class=\"GtkLabel\" id=\"label16\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"xalign\">0</property><property name=\"label\" translatable=\"yes\""
  ">Opacity of popup wi_ndows:</property><property name=\"use_underline\">"
  "True</property><property name=\"mnemonic_widget\">popup_opacity_scale</"
  "property></object><packing><property name=\"expand\">False</property><p"
  "roperty name=\"fill\">False</property><property name=\"position\">14</p"
  "roperty></packing></child><child><object class=\"GtkAlignment\" id=\"al"
  "ignment9\"><property name=\"visible\">True</property><property name=\"c"
  "an_focus\">False</property><property name=\"top_padding\">2</property><"
  "property name=\"left_padding\">12</property><child><object class=\"GtkH"
  "Box\" id=\"hbox7\"><property name=\"visible\">True</property><property "
  "name=\"can_focus\">False</property><child><object class=\"GtkLabel\" id"
  "=\"label25\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><property name=\"label\" translatable=\"yes"
  "\">&lt;i&gt;Transparent&lt;/i&gt;</property><property name=\"use_markup"
  "\">True</property></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">False</property><property name=\"positio"
  "n\">0</property></packing></child><child><object class=\"GtkHScale\" id"
  "=\"popup_opacity_scale\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">True</property><property name=\"update_policy\""
  ">discontinuous</property><property name=\"adjustment\">adjustment6</pro"
  "perty><property name=\"restrict_to_fill_level\">False</property><proper"
  "ty name=\"draw_value\">False</property></object><packing><property name"
  "=\"expand\">True</property><property name=\"fill\">True</property><prop"
  "erty name=\"position\">1</property></packing></child><child><object cla"
  "ss=\"GtkLabel\" id=\"label26\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"label\""
  " translatable=\"yes\">&lt;i&gt;Opaque&lt;/i&gt;</property><property nam"
  "e=\"use_markup\">True</property></object><packing><property name=\"expa"
  "nd\">False</property><property name=\"fill\">False</property><property "
  "name=\"position\">2</property></packing></child></object></child></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">False</property><property name=\"position\">15</property></packi"
  "ng></child></object></child></object></child></object></child></object>"
  "<packing><property name=\"expand\">True</property><property name=\"fill"
  "\">True</property><property name=\"position\">1</property></packing></c"
  "hild></object><packing><property name=\"position\">5</property></packin"
  "g></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"label6\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"label\" translatable=\"yes\">C_omposit"
  "or</property><property name=\"use_underline\">True</property></object><"
  "packing><property name=\"position\">5</property><property name=\"tab_fi"
  "ll\">False</property></packing></child></object><packing><property name"
  "=\"expand\">True</property><property name=\"fill\">True</property><prop"
  "erty name=\"position\">1</property></packing></child></object></child><"
  "action-widgets><action-widget response=\"-11\">button2</action-widget><"
  "action-widget response=\"0\">button1</action-widget></action-widgets></"
  "object></interface>"
};

static const unsigned tweaks_dialog_ui_length = 45132u;

