/* automatically generated from xfwm4-dialog.glade */
#ifdef __SUNPRO_C
#pragma align 4 (xfwm4_dialog_ui)
#endif
#ifdef __GNUC__
static const char xfwm4_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char xfwm4_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"2.24\"/><object class=\"GtkAdjustment\" id=\"adjustment1"
  "\"><property name=\"lower\">5</property><property name=\"upper\">2000</"
  "property><property name=\"value\">5</property><property name=\"step_inc"
  "rement\">1</property><property name=\"page_increment\">10</property></o"
  "bject><object class=\"GtkAdjustment\" id=\"adjustment2\"><property name"
  "=\"lower\">5</property><property name=\"upper\">2000</property><propert"
  "y name=\"value\">5</property><property name=\"step_increment\">1</prope"
  "rty><property name=\"page_increment\">10</property></object><object cla"
  "ss=\"GtkAdjustment\" id=\"adjustment3\"><property name=\"lower\">5</pro"
  "perty><property name=\"upper\">100</property><property name=\"value\">2"
  "0</property><property name=\"step_increment\">1</property><property nam"
  "e=\"page_increment\">10</property></object><object class=\"GtkAdjustmen"
  "t\" id=\"adjustment4\"><property name=\"lower\">5</property><property n"
  "ame=\"upper\">100</property><property name=\"value\">20</property><prop"
  "erty name=\"step_increment\">1</property><property name=\"page_incremen"
  "t\">10</property></object><object class=\"XfceTitledDialog\" id=\"main-"
  "dialog\"><property name=\"can_focus\">False</property><property name=\""
  "title\" translatable=\"yes\">Window Manager</property><property name=\""
  "window_position\">center-on-parent</property><property name=\"icon_name"
  "\">xfwm4</property><property name=\"type_hint\">dialog</property><prope"
  "rty name=\"subtitle\" translatable=\"yes\">Configure window behavior an"
  "d shortcuts</property><child internal-child=\"vbox\"><object class=\"Gt"
  "kVBox\" id=\"main-vbox\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><child internal-child=\"action"
  "_area\"><object class=\"GtkHButtonBox\" id=\"dialog-action_area1\"><pro"
  "perty name=\"visible\">True</property><property name=\"can_focus\">Fals"
  "e</property><property name=\"layout_style\">end</property><child><objec"
  "t class=\"GtkButton\" id=\"help_button\"><property name=\"label\">gtk-h"
  "elp</property><property name=\"use_action_appearance\">False</property>"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "True</property><property name=\"receives_default\">True</property><prop"
  "erty name=\"use_stock\">True</property></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">False</property><pr"
  "operty name=\"position\">0</property><property name=\"secondary\">True<"
  "/property></packing></child><child><object class=\"GtkButton\" id=\"clo"
  "se_button\"><property name=\"label\">gtk-close</property><property name"
  "=\"use_action_appearance\">False</property><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">True</property><property nam"
  "e=\"receives_default\">True</property><property name=\"use_stock\">True"
  "</property></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">False</property><property name=\"position\">1</"
  "property></packing></child></object><packing><property name=\"expand\">"
  "False</property><property name=\"fill\">True</property><property name=\""
  "pack_type\">end</property><property name=\"position\">0</property></pac"
  "king></child><child><object class=\"GtkNotebook\" id=\"plug-child\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Tru"
  "e</property><property name=\"border_width\">6</property><child><object "
  "class=\"GtkHBox\" id=\"hbox7\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"border_"
  "width\">12</property><property name=\"spacing\">12</property><child><ob"
  "ject class=\"GtkFrame\" id=\"frame13\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "label_xalign\">0</property><property name=\"shadow_type\">none</propert"
  "y><child><object class=\"GtkAlignment\" id=\"alignment11\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"top_padding\">6</property><property name=\"left_pa"
  "dding\">12</property><child><object class=\"GtkScrolledWindow\" id=\"sc"
  "rolledwindow3\"><property name=\"width_request\">200</property><propert"
  "y name=\"visible\">True</property><property name=\"can_focus\">True</pr"
  "operty><property name=\"hscrollbar_policy\">automatic</property><proper"
  "ty name=\"vscrollbar_policy\">automatic</property><property name=\"shad"
  "ow_type\">in</property><child><object class=\"GtkTreeView\" id=\"theme_"
  "name_treeview\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">True</property><property name=\"headers_visible\">False"
  "</property></object></child></object></child></object></child><child ty"
  "pe=\"label\"><object class=\"GtkLabel\" id=\"label32\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">&lt;b&gt;The_me&lt;/b&gt;<"
  "/property><property name=\"use_markup\">True</property><property name=\""
  "use_underline\">True</property></object></child></object><packing><prop"
  "erty name=\"expand\">True</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">0</property></packing></child><child><o"
  "bject class=\"GtkVBox\" id=\"vbox12\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "spacing\">6</property><child><object class=\"GtkFrame\" id=\"frame10\">"
  "<property name=\"visible\">True</property><property name=\"can_focus\">"
  "False</property><property name=\"label_xalign\">0</property><property n"
  "ame=\"shadow_type\">none</property><child><object class=\"GtkAlignment\""
  " id=\"alignment14\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"border_width\">6</"
  "property><property name=\"bottom_padding\">6</property><property name=\""
  "left_padding\">12</property><child><object class=\"GtkFontButton\" id=\""
  "title_font_button\"><property name=\"use_action_appearance\">False</pro"
  "perty><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">True</property><property name=\"receives_default\">True</property"
  "></object></child></object></child><child type=\"label\"><object class="
  "\"GtkLabel\" id=\"label23\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"label\" tr"
  "anslatable=\"yes\">&lt;b&gt;Title fon_t&lt;/b&gt;</property><property n"
  "ame=\"use_markup\">True</property><property name=\"use_underline\">True"
  "</property><property name=\"mnemonic_widget\">title_font_button</proper"
  "ty></object></child></object><packing><property name=\"expand\">False</"
  "property><property name=\"fill\">False</property><property name=\"posit"
  "ion\">0</property></packing></child><child><object class=\"GtkFrame\" i"
  "d=\"frame11\"><property name=\"visible\">True</property><property name="
  "\"can_focus\">False</property><property name=\"label_xalign\">0</proper"
  "ty><property name=\"shadow_type\">none</property><child><object class=\""
  "GtkAlignment\" id=\"title_align_box\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "border_width\">6</property><property name=\"bottom_padding\">6</propert"
  "y><property name=\"left_padding\">12</property><child><object class=\"G"
  "tkComboBox\" id=\"title_align_combo\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property></object></child>"
  "</object></child><child type=\"label\"><object class=\"GtkLabel\" id=\""
  "label24\"><property name=\"visible\">True</property><property name=\"ca"
  "n_focus\">False</property><property name=\"label\" translatable=\"yes\""
  ">&lt;b&gt;Title _alignment&lt;/b&gt;</property><property name=\"use_mar"
  "kup\">True</property><property name=\"use_underline\">True</property><p"
  "roperty name=\"mnemonic_widget\">title_align_combo</property></object><"
  "/child></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">False</property><property name=\"position\">1</prop"
  "erty></packing></child><child><object class=\"GtkFrame\" id=\"frame12\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label_xalign\">0</property><property "
  "name=\"shadow_type\">none</property><child><object class=\"GtkAlignment"
  "\" id=\"button_layout_box\"><property name=\"visible\">True</property><"
  "property name=\"can_focus\">False</property><property name=\"bottom_pad"
  "ding\">6</property><property name=\"left_padding\">12</property><child>"
  "<object class=\"GtkVBox\" id=\"vbox13\"><property name=\"visible\">True"
  "</property><property name=\"can_focus\">False</property><property name="
  "\"border_width\">6</property><property name=\"spacing\">6</property><ch"
  "ild><object class=\"GtkLabel\" id=\"label26\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"xalign\">0</property><property name=\"label\" translatable=\"yes"
  "\">Click and drag the buttons to change the layout</property></object><"
  "packing><property name=\"expand\">True</property><property name=\"fill\""
  ">True</property><property name=\"position\">0</property></packing></chi"
  "ld><child><object class=\"GtkFrame\" id=\"active-frame\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"label_xalign\">0</property><child><object class=\"Gt"
  "kAlignment\" id=\"alignment17\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"border"
  "_width\">6</property><child><object class=\"GtkHBox\" id=\"active-box\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><child><object class=\"GtkButton\" id=\"button-layout-"
  "|\"><property name=\"label\" translatable=\"yes\">Title</property><prop"
  "erty name=\"use_action_appearance\">False</property><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"receives_default\">True</property><property name=\"tooltip"
  "_text\" translatable=\"yes\">The window title cannot be removed</proper"
  "ty></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">False</property><property name=\"position\">0</property"
  "></packing></child></object></child></object></child><child type=\"labe"
  "l\"><object class=\"GtkLabel\" id=\"label27\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"label\" translatable=\"yes\">Active</property><property name=\"u"
  "se_markup\">True</property></object></child></object><packing><property"
  " name=\"expand\">True</property><property name=\"fill\">True</property>"
  "<property name=\"position\">1</property></packing></child><child><objec"
  "t class=\"GtkFrame\" id=\"hidden-frame\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"label_xalign\">0</property><child><object class=\"GtkAlignment\" id="
  "\"alignment18\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"border_width\">6</prop"
  "erty><child><object class=\"GtkHBox\" id=\"hidden-box\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"spacing\">6</property><child><object class=\"GtkButto"
  "n\" id=\"button-layout-O\"><property name=\"use_action_appearance\">Fal"
  "se</property><property name=\"visible\">True</property><property name=\""
  "can_focus\">True</property><property name=\"receives_default\">True</pr"
  "operty><property name=\"tooltip_text\" translatable=\"yes\">Menu</prope"
  "rty><child><object class=\"GtkImage\" id=\"image1\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"icon_name\">xfce-wm-menu</property></object></child></obj"
  "ect><packing><property name=\"expand\">False</property><property name=\""
  "fill\">False</property><property name=\"position\">0</property></packin"
  "g></child><child><object class=\"GtkButton\" id=\"button-layout-T\"><pr"
  "operty name=\"use_action_appearance\">False</property><property name=\""
  "visible\">True</property><property name=\"can_focus\">True</property><p"
  "roperty name=\"receives_default\">True</property><property name=\"toolt"
  "ip_text\" translatable=\"yes\">Stick</property><child><object class=\"G"
  "tkImage\" id=\"image2\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">False</property><property name=\"icon_name\">xf"
  "ce-wm-stick</property></object></child></object><packing><property name"
  "=\"expand\">False</property><property name=\"fill\">False</property><pr"
  "operty name=\"position\">1</property></packing></child><child><object c"
  "lass=\"GtkButton\" id=\"button-layout-S\"><property name=\"use_action_a"
  "ppearance\">False</property><property name=\"visible\">True</property><"
  "property name=\"can_focus\">True</property><property name=\"receives_de"
  "fault\">True</property><property name=\"tooltip_text\" translatable=\"y"
  "es\">Shade</property><child><object class=\"GtkImage\" id=\"image3\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"icon_name\">xfce-wm-shade</property></ob"
  "ject></child></object><packing><property name=\"expand\">False</propert"
  "y><property name=\"fill\">False</property><property name=\"position\">2"
  "</property></packing></child><child><object class=\"GtkButton\" id=\"bu"
  "tton-layout-H\"><property name=\"use_action_appearance\">False</propert"
  "y><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"receives_default\">True</property><pro"
  "perty name=\"tooltip_text\" translatable=\"yes\">Minimize</property><ch"
  "ild><object class=\"GtkImage\" id=\"image4\"><property name=\"visible\""
  ">True</property><property name=\"can_focus\">False</property><property "
  "name=\"icon_name\">xfce-wm-minimize</property></object></child></object"
  "><packing><property name=\"expand\">False</property><property name=\"fi"
  "ll\">False</property><property name=\"position\">3</property></packing>"
  "</child><child><object class=\"GtkButton\" id=\"button-layout-M\"><prop"
  "erty name=\"use_action_appearance\">False</property><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">True</property><pro"
  "perty name=\"receives_default\">True</property><property name=\"tooltip"
  "_text\" translatable=\"yes\">Maximize</property><child><object class=\""
  "GtkImage\" id=\"image5\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"icon_name\">x"
  "fce-wm-maximize</property></object></child></object><packing><property "
  "name=\"expand\">False</property><property name=\"fill\">False</property"
  "><property name=\"position\">4</property></packing></child><child><obje"
  "ct class=\"GtkButton\" id=\"button-layout-C\"><property name=\"use_acti"
  "on_appearance\">False</property><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">True</property><property name=\"receive"
  "s_default\">True</property><property name=\"tooltip_text\" translatable"
  "=\"yes\">Close</property><child><object class=\"GtkImage\" id=\"image6\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"icon_name\">xfce-wm-close</property><"
  "/object></child></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">5</property></packing></child></object></child></object></child><child"
  " type=\"label\"><object class=\"GtkLabel\" id=\"label28\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"label\" translatable=\"yes\">Hidden</property><prop"
  "erty name=\"use_markup\">True</property></object></child></object><pack"
  "ing><property name=\"expand\">True</property><property name=\"fill\">Tr"
  "ue</property><property name=\"position\">2</property></packing></child>"
  "</object></child></object></child><child type=\"label\"><object class=\""
  "GtkLabel\" id=\"label25\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"label\" tran"
  "slatable=\"yes\">&lt;b&gt;Button layout&lt;/b&gt;</property><property n"
  "ame=\"use_markup\">True</property></object></child></object><packing><p"
  "roperty name=\"expand\">False</property><property name=\"fill\">False</"
  "property><property name=\"position\">2</property></packing></child></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">1</property></packing"
  "></child></object></child><child type=\"tab\"><object class=\"GtkLabel\""
  " id=\"label1\"><property name=\"visible\">True</property><property name"
  "=\"can_focus\">False</property><property name=\"label\" translatable=\""
  "yes\">_Style</property><property name=\"use_underline\">True</property>"
  "</object><packing><property name=\"tab_fill\">False</property></packing"
  "></child><child><object class=\"GtkVBox\" id=\"vbox10\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"border_width\">12</property><property name=\"spacing\""
  ">6</property><child><object class=\"GtkLabel\" id=\"label22\"><property"
  " name=\"visible\">True</property><property name=\"can_focus\">False</pr"
  "operty><property name=\"xalign\">0</property><property name=\"label\" t"
  "ranslatable=\"yes\">Define shortcuts to perform _window manager actions"
  ":</property><property name=\"use_markup\">True</property><property name"
  "=\"use_underline\">True</property></object><packing><property name=\"ex"
  "pand\">False</property><property name=\"fill\">False</property><propert"
  "y name=\"position\">0</property></packing></child><child><object class="
  "\"GtkVBox\" id=\"vbox11\"><property name=\"visible\">True</property><pr"
  "operty name=\"can_focus\">False</property><property name=\"spacing\">6<"
  "/property><child><object class=\"GtkScrolledWindow\" id=\"scrolledwindo"
  "w2\"><property name=\"visible\">True</property><property name=\"can_foc"
  "us\">True</property><property name=\"hscrollbar_policy\">never</propert"
  "y><property name=\"vscrollbar_policy\">automatic</property><property na"
  "me=\"shadow_type\">in</property><child><object class=\"GtkTreeView\" id"
  "=\"shortcuts_treeview\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property></object></child></object><packi"
  "ng><property name=\"expand\">True</property><property name=\"fill\">Tru"
  "e</property><property name=\"position\">0</property></packing></child><"
  "child><placeholder/></child></object><packing><property name=\"expand\""
  ">True</property><property name=\"fill\">True</property><property name=\""
  "position\">1</property></packing></child><child><object class=\"GtkAlig"
  "nment\" id=\"alignment15\"><property name=\"visible\">True</property><p"
  "roperty name=\"can_focus\">False</property><property name=\"yalign\">0<"
  "/property><property name=\"xscale\">0</property><child><object class=\""
  "GtkHBox\" id=\"hbox5\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"spacing\">6</pr"
  "operty><child><object class=\"GtkButton\" id=\"shortcuts_edit_button\">"
  "<property name=\"label\">gtk-edit</property><property name=\"use_action"
  "_appearance\">False</property><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"receives_"
  "default\">True</property><property name=\"use_stock\">True</property></"
  "object><packing><property name=\"expand\">False</property><property nam"
  "e=\"fill\">False</property><property name=\"position\">0</property></pa"
  "cking></child><child><object class=\"GtkButton\" id=\"shortcuts_clear_b"
  "utton\"><property name=\"label\">gtk-clear</property><property name=\"u"
  "se_action_appearance\">False</property><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">True</property><property name=\""
  "receives_default\">True</property><property name=\"use_stock\">True</pr"
  "operty></object><packing><property name=\"expand\">False</property><pro"
  "perty name=\"fill\">False</property><property name=\"position\">1</prop"
  "erty></packing></child><child><object class=\"GtkButton\" id=\"shortcut"
  "s_reset_button\"><property name=\"label\" translatable=\"yes\">_Reset t"
  "o Defaults</property><property name=\"use_action_appearance\">False</pr"
  "operty><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">True</property><property name=\"receives_default\">True</propert"
  "y><property name=\"use_underline\">True</property></object><packing><pr"
  "operty name=\"expand\">False</property><property name=\"fill\">False</p"
  "roperty><property name=\"padding\">15</property><property name=\"pack_t"
  "ype\">end</property><property name=\"position\">2</property></packing><"
  "/child></object></child></object><packing><property name=\"expand\">Fal"
  "se</property><property name=\"fill\">False</property><property name=\"p"
  "osition\">2</property></packing></child></object><packing><property nam"
  "e=\"position\">1</property></packing></child><child type=\"tab\"><objec"
  "t class=\"GtkLabel\" id=\"label2\"><property name=\"visible\">True</pro"
  "perty><property name=\"can_focus\">False</property><property name=\"lab"
  "el\" translatable=\"yes\">_Keyboard</property><property name=\"use_unde"
  "rline\">True</property></object><packing><property name=\"position\">1<"
  "/property><property name=\"tab_fill\">False</property></packing></child"
  "><child><object class=\"GtkVBox\" id=\"vbox7\"><property name=\"visible"
  "\">True</property><property name=\"can_focus\">False</property><propert"
  "y name=\"border_width\">12</property><property name=\"spacing\">6</prop"
  "erty><child><object class=\"GtkFrame\" id=\"frame5\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"label_xalign\">0</property><property name=\"shadow_type\""
  ">none</property><child><object class=\"GtkAlignment\" id=\"alignment7\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"border_width\">6</property><property "
  "name=\"bottom_padding\">6</property><property name=\"left_padding\">12<"
  "/property><child><object class=\"GtkVBox\" id=\"vbox14\"><property name"
  "=\"visible\">True</property><property name=\"can_focus\">False</propert"
  "y><property name=\"spacing\">6</property><child><object class=\"GtkHBox"
  "\" id=\"hbox3\"><property name=\"visible\">True</property><property nam"
  "e=\"can_focus\">False</property><property name=\"spacing\">12</property"
  "><property name=\"homogeneous\">True</property><child><object class=\"G"
  "tkRadioButton\" id=\"click_to_focus_radio\"><property name=\"label\" tr"
  "anslatable=\"yes\">Click to foc_us</property><property name=\"use_actio"
  "n_appearance\">False</property><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">True</property><property name=\"receives"
  "_default\">False</property><property name=\"use_underline\">True</prope"
  "rty><property name=\"draw_indicator\">True</property></object><packing>"
  "<property name=\"expand\">True</property><property name=\"fill\">True</"
  "property><property name=\"position\">0</property></packing></child><chi"
  "ld><object class=\"GtkRadioButton\" id=\"focus_follows_mouse_radio\"><p"
  "roperty name=\"label\" translatable=\"yes\">Focus follows _mouse</prope"
  "rty><property name=\"use_action_appearance\">False</property><property "
  "name=\"visible\">True</property><property name=\"can_focus\">True</prop"
  "erty><property name=\"receives_default\">False</property><property name"
  "=\"use_underline\">True</property><property name=\"draw_indicator\">Tru"
  "e</property><property name=\"group\">click_to_focus_radio</property></o"
  "bject><packing><property name=\"expand\">True</property><property name="
  "\"fill\">True</property><property name=\"position\">1</property></packi"
  "ng></child></object><packing><property name=\"expand\">True</property><"
  "property name=\"fill\">True</property><property name=\"position\">0</pr"
  "operty></packing></child><child><object class=\"GtkLabel\" id=\"label29"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"xalign\">0</property><property name"
  "=\"label\" translatable=\"yes\">_Delay before window receives focus:</p"
  "roperty><property name=\"use_markup\">True</property><property name=\"u"
  "se_underline\">True</property><property name=\"mnemonic_widget\">focus_"
  "delay_scale</property></object><packing><property name=\"expand\">True<"
  "/property><property name=\"fill\">True</property><property name=\"posit"
  "ion\">1</property></packing></child><child><object class=\"GtkAlignment"
  "\" id=\"alignment19\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"left_padding\">1"
  "2</property><child><object class=\"GtkHBox\" id=\"focus_delay_hbox\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"spacing\">12</property><child><object cl"
  "ass=\"GtkLabel\" id=\"label30\"><property name=\"visible\">True</proper"
  "ty><property name=\"can_focus\">False</property><property name=\"label\""
  " translatable=\"yes\" comments=\"Focus delay\">&lt;i&gt;Short&lt;/i&gt;"
  "</property><property name=\"use_markup\">True</property></object><packi"
  "ng><property name=\"expand\">False</property><property name=\"fill\">Fa"
  "lse</property><property name=\"position\">0</property></packing></child"
  "><child><object class=\"GtkHScale\" id=\"focus_delay_scale\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">True</prop"
  "erty><property name=\"update_policy\">discontinuous</property><property"
  " name=\"adjustment\">adjustment1</property><property name=\"draw_value\""
  ">False</property></object><packing><property name=\"expand\">True</prop"
  "erty><property name=\"fill\">True</property><property name=\"position\""
  ">1</property></packing></child><child><object class=\"GtkLabel\" id=\"l"
  "abel31\"><property name=\"visible\">True</property><property name=\"can"
  "_focus\">False</property><property name=\"label\" translatable=\"yes\" "
  "comments=\"Focus delay\">&lt;i&gt;Long&lt;/i&gt;</property><property na"
  "me=\"use_markup\">True</property></object><packing><property name=\"exp"
  "and\">False</property><property name=\"fill\">False</property><property"
  " name=\"position\">2</property></packing></child></object></child></obj"
  "ect><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">2</property></packing"
  "></child></object></child></object></child><child type=\"label\"><objec"
  "t class=\"GtkLabel\" id=\"label15\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"la"
  "bel\" translatable=\"yes\">&lt;b&gt;Focus model&lt;/b&gt;</property><pr"
  "operty name=\"use_markup\">True</property></object></child></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">0</property></packing></ch"
  "ild><child><object class=\"GtkFrame\" id=\"frame6\"><property name=\"vi"
  "sible\">True</property><property name=\"can_focus\">False</property><pr"
  "operty name=\"label_xalign\">0</property><property name=\"shadow_type\""
  ">none</property><child><object class=\"GtkAlignment\" id=\"alignment8\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"border_width\">6</property><property "
  "name=\"bottom_padding\">6</property><property name=\"left_padding\">12<"
  "/property><child><object class=\"GtkCheckButton\" id=\"focus_new_check\""
  "><property name=\"label\" translatable=\"yes\">Automatically give focus"
  " to _newly created windows</property><property name=\"use_action_appear"
  "ance\">False</property><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">True</property><property name=\"receives_default"
  "\">False</property><property name=\"use_underline\">True</property><pro"
  "perty name=\"draw_indicator\">True</property></object></child></object>"
  "</child><child type=\"label\"><object class=\"GtkLabel\" id=\"label16\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"label\" translatable=\"yes\">&lt;b&gt"
  ";New window focus&lt;/b&gt;</property><property name=\"use_markup\">Tru"
  "e</property></object></child></object><packing><property name=\"expand\""
  ">False</property><property name=\"fill\">False</property><property name"
  "=\"position\">1</property></packing></child><child><object class=\"GtkF"
  "rame\" id=\"frame7\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"label_xalign\">0<"
  "/property><property name=\"shadow_type\">none</property><child><object "
  "class=\"GtkAlignment\" id=\"alignment9\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"border_width\">6</property><property name=\"bottom_padding\">6</prop"
  "erty><property name=\"left_padding\">12</property><child><object class="
  "\"GtkVBox\" id=\"vbox8\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"spacing\">6</"
  "property><child><object class=\"GtkCheckButton\" id=\"raise_on_focus_ch"
  "eck\"><property name=\"label\" translatable=\"yes\">Automatically _rais"
  "e windows when they receive focus</property><property name=\"use_action"
  "_appearance\">False</property><property name=\"visible\">True</property"
  "><property name=\"can_focus\">True</property><property name=\"receives_"
  "default\">False</property><property name=\"use_underline\">True</proper"
  "ty><property name=\"draw_indicator\">True</property></object><packing><"
  "property name=\"expand\">True</property><property name=\"fill\">True</p"
  "roperty><property name=\"position\">0</property></packing></child><chil"
  "d><object class=\"GtkVBox\" id=\"vbox9\"><property name=\"visible\">Tru"
  "e</property><property name=\"can_focus\">False</property><property name"
  "=\"spacing\">6</property><child><object class=\"GtkLabel\" id=\"label19"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"xalign\">0</property><property name"
  "=\"label\" translatable=\"yes\">Delay _before raising focused window:</"
  "property><property name=\"use_underline\">True</property><property name"
  "=\"mnemonic_widget\">focus_raise_delay_scale</property></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Fal"
  "se</property><property name=\"position\">0</property></packing></child>"
  "<child><object class=\"GtkAlignment\" id=\"alignment1\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"left_padding\">12</property><child><object class=\"Gt"
  "kHBox\" id=\"hbox4\"><property name=\"visible\">True</property><propert"
  "y name=\"can_focus\">False</property><property name=\"spacing\">12</pro"
  "perty><child><object class=\"GtkLabel\" id=\"label20\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\" comments=\"Raise focus del"
  "ay\">&lt;i&gt;Short&lt;/i&gt;</property><property name=\"use_markup\">T"
  "rue</property></object><packing><property name=\"expand\">False</proper"
  "ty><property name=\"fill\">False</property><property name=\"position\">"
  "0</property></packing></child><child><object class=\"GtkHScale\" id=\"f"
  "ocus_raise_delay_scale\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">True</property><property name=\"update_policy\""
  ">discontinuous</property><property name=\"adjustment\">adjustment2</pro"
  "perty><property name=\"draw_value\">False</property></object><packing><"
  "property name=\"expand\">True</property><property name=\"fill\">True</p"
  "roperty><property name=\"position\">1</property></packing></child><chil"
  "d><object class=\"GtkLabel\" id=\"label21\"><property name=\"visible\">"
  "True</property><property name=\"can_focus\">False</property><property n"
  "ame=\"label\" translatable=\"yes\" comments=\"Raise focus delay\">&lt;i"
  "&gt;Long&lt;/i&gt;</property><property name=\"use_markup\">True</proper"
  "ty></object><packing><property name=\"expand\">False</property><propert"
  "y name=\"fill\">False</property><property name=\"position\">2</property"
  "></packing></child></object></child></object><packing><property name=\""
  "expand\">True</property><property name=\"fill\">True</property><propert"
  "y name=\"position\">1</property></packing></child></object><packing><pr"
  "operty name=\"expand\">True</property><property name=\"fill\">True</pro"
  "perty><property name=\"position\">1</property></packing></child></objec"
  "t></child></object></child><child type=\"label\"><object class=\"GtkLab"
  "el\" id=\"label17\"><property name=\"visible\">True</property><property"
  " name=\"can_focus\">False</property><property name=\"label\" translatab"
  "le=\"yes\">&lt;b&gt;Raise on focus&lt;/b&gt;</property><property name=\""
  "use_markup\">True</property></object></child></object><packing><propert"
  "y name=\"expand\">False</property><property name=\"fill\">False</proper"
  "ty><property name=\"position\">2</property></packing></child><child><ob"
  "ject class=\"GtkFrame\" id=\"frame8\"><property name=\"visible\">True</"
  "property><property name=\"can_focus\">False</property><property name=\""
  "label_xalign\">0</property><property name=\"shadow_type\">none</propert"
  "y><child><object class=\"GtkAlignment\" id=\"alignment10\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"border_width\">6</property><property name=\"bottom"
  "_padding\">6</property><property name=\"left_padding\">12</property><ch"
  "ild><object class=\"GtkCheckButton\" id=\"raise_on_click_check\"><prope"
  "rty name=\"label\" translatable=\"yes\">Raise window when clicking _ins"
  "ide application window</property><property name=\"use_action_appearance"
  "\">False</property><property name=\"visible\">True</property><property "
  "name=\"can_focus\">True</property><property name=\"receives_default\">F"
  "alse</property><property name=\"use_underline\">True</property><propert"
  "y name=\"draw_indicator\">True</property></object></child></object></ch"
  "ild><child type=\"label\"><object class=\"GtkLabel\" id=\"label18\"><pr"
  "operty name=\"visible\">True</property><property name=\"can_focus\">Fal"
  "se</property><property name=\"label\" translatable=\"yes\">&lt;b&gt;Rai"
  "se on click&lt;/b&gt;</property><property name=\"use_markup\">True</pro"
  "perty></object></child></object><packing><property name=\"expand\">Fals"
  "e</property><property name=\"fill\">False</property><property name=\"po"
  "sition\">3</property></packing></child></object><packing><property name"
  "=\"position\">2</property></packing></child><child type=\"tab\"><object"
  " class=\"GtkLabel\" id=\"label3\"><property name=\"visible\">True</prop"
  "erty><property name=\"can_focus\">False</property><property name=\"labe"
  "l\" translatable=\"yes\">_Focus</property><property name=\"use_underlin"
  "e\">True</property></object><packing><property name=\"position\">2</pro"
  "perty><property name=\"tab_fill\">False</property></packing></child><ch"
  "ild><object class=\"GtkVBox\" id=\"vbox1\"><property name=\"visible\">T"
  "rue</property><property name=\"can_focus\">False</property><property na"
  "me=\"border_width\">12</property><property name=\"spacing\">6</property"
  "><child><object class=\"GtkFrame\" id=\"frame1\"><property name=\"visib"
  "le\">True</property><property name=\"can_focus\">False</property><prope"
  "rty name=\"label_xalign\">0</property><property name=\"shadow_type\">no"
  "ne</property><child><object class=\"GtkAlignment\" id=\"alignment2\"><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Fa"
  "lse</property><property name=\"border_width\">6</property><property nam"
  "e=\"bottom_padding\">6</property><property name=\"left_padding\">12</pr"
  "operty><child><object class=\"GtkVBox\" id=\"vbox2\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"spacing\">6</property><child><object class=\"GtkHBox\" i"
  "d=\"hbox8\"><property name=\"visible\">True</property><property name=\""
  "can_focus\">False</property><child><object class=\"GtkCheckButton\" id="
  "\"snap_to_border_check\"><property name=\"label\" translatable=\"yes\">"
  "To screen _borders</property><property name=\"use_action_appearance\">F"
  "alse</property><property name=\"visible\">True</property><property name"
  "=\"can_focus\">True</property><property name=\"receives_default\">False"
  "</property><property name=\"use_underline\">True</property><property na"
  "me=\"draw_indicator\">True</property></object><packing><property name=\""
  "expand\">True</property><property name=\"fill\">True</property><propert"
  "y name=\"position\">0</property></packing></child><child><object class="
  "\"GtkCheckButton\" id=\"snap_to_window_check\"><property name=\"label\""
  " translatable=\"yes\">To other _windows</property><property name=\"use_"
  "action_appearance\">False</property><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">True</property><property name=\"rec"
  "eives_default\">False</property><property name=\"use_underline\">True</"
  "property><property name=\"draw_indicator\">True</property></object><pac"
  "king><property name=\"expand\">True</property><property name=\"fill\">T"
  "rue</property><property name=\"position\">1</property></packing></child"
  "></object><packing><property name=\"expand\">True</property><property n"
  "ame=\"fill\">True</property><property name=\"position\">0</property></p"
  "acking></child><child><object class=\"GtkVBox\" id=\"vbox5\"><property "
  "name=\"visible\">True</property><property name=\"can_focus\">False</pro"
  "perty><property name=\"spacing\">6</property><child><object class=\"Gtk"
  "Label\" id=\"label9\"><property name=\"visible\">True</property><proper"
  "ty name=\"can_focus\">False</property><property name=\"xalign\">0</prop"
  "erty><property name=\"label\" translatable=\"yes\">Dis_tance:</property"
  "><property name=\"use_underline\">True</property><property name=\"mnemo"
  "nic_widget\">snap_width_scale</property></object><packing><property nam"
  "e=\"expand\">True</property><property name=\"fill\">True</property><pro"
  "perty name=\"position\">0</property></packing></child><child><object cl"
  "ass=\"GtkAlignment\" id=\"alignment6\"><property name=\"visible\">True<"
  "/property><property name=\"can_focus\">False</property><property name=\""
  "left_padding\">12</property><child><object class=\"GtkHBox\" id=\"hbox1"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"spacing\">12</property><child><obje"
  "ct class=\"GtkLabel\" id=\"label11\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><property name=\"l"
  "abel\" translatable=\"yes\" comments=\"Snapping distance\">&lt;i&gt;Sma"
  "ll&lt;/i&gt;</property><property name=\"use_markup\">True</property></o"
  "bject><packing><property name=\"expand\">False</property><property name"
  "=\"fill\">False</property><property name=\"position\">0</property></pac"
  "king></child><child><object class=\"GtkHScale\" id=\"snap_width_scale\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">True</property><property name=\"update_policy\">discontinuous</propert"
  "y><property name=\"adjustment\">adjustment3</property><property name=\""
  "restrict_to_fill_level\">False</property><property name=\"draw_value\">"
  "False</property></object><packing><property name=\"expand\">True</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "1</property></packing></child><child><object class=\"GtkLabel\" id=\"la"
  "bel12\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"label\" translatable=\"yes\" c"
  "omments=\"Snapping distance\">&lt;i&gt;Wide&lt;/i&gt;</property><proper"
  "ty name=\"use_markup\">True</property></object><packing><property name="
  "\"expand\">False</property><property name=\"fill\">False</property><pro"
  "perty name=\"position\">2</property></packing></child></object></child>"
  "</object><packing><property name=\"expand\">True</property><property na"
  "me=\"fill\">True</property><property name=\"position\">1</property></pa"
  "cking></child></object><packing><property name=\"expand\">True</propert"
  "y><property name=\"fill\">True</property><property name=\"position\">1<"
  "/property></packing></child></object></child></object></child><child ty"
  "pe=\"label\"><object class=\"GtkLabel\" id=\"label5\"><property name=\""
  "visible\">True</property><property name=\"can_focus\">False</property><"
  "property name=\"label\" translatable=\"yes\">&lt;b&gt;Windows snapping&"
  "lt;/b&gt;</property><property name=\"use_markup\">True</property></obje"
  "ct></child></object><packing><property name=\"expand\">False</property>"
  "<property name=\"fill\">True</property><property name=\"position\">0</p"
  "roperty></packing></child><child><object class=\"GtkFrame\" id=\"frame2"
  "\"><property name=\"visible\">True</property><property name=\"can_focus"
  "\">False</property><property name=\"label_xalign\">0</property><propert"
  "y name=\"shadow_type\">none</property><child><object class=\"GtkAlignme"
  "nt\" id=\"alignment3\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"border_width\">"
  "6</property><property name=\"bottom_padding\">6</property><property nam"
  "e=\"left_padding\">12</property><child><object class=\"GtkVBox\" id=\"v"
  "box4\"><property name=\"visible\">True</property><property name=\"can_f"
  "ocus\">False</property><property name=\"spacing\">6</property><child><o"
  "bject class=\"GtkHBox\" id=\"hbox9\"><property name=\"visible\">True</p"
  "roperty><property name=\"can_focus\">False</property><child><object cla"
  "ss=\"GtkCheckButton\" id=\"wrap_workspaces_check\"><property name=\"lab"
  "el\" translatable=\"yes\">With the mouse _pointer</property><property n"
  "ame=\"use_action_appearance\">False</property><property name=\"visible\""
  ">True</property><property name=\"can_focus\">True</property><property n"
  "ame=\"receives_default\">False</property><property name=\"use_underline"
  "\">True</property><property name=\"draw_indicator\">True</property></ob"
  "ject><packing><property name=\"expand\">True</property><property name=\""
  "fill\">True</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkCheckButton\" id=\"wrap_windows_chec"
  "k\"><property name=\"label\" translatable=\"yes\">With a _dragged windo"
  "w</property><property name=\"use_action_appearance\">False</property><p"
  "roperty name=\"visible\">True</property><property name=\"can_focus\">Tr"
  "ue</property><property name=\"receives_default\">False</property><prope"
  "rty name=\"use_underline\">True</property><property name=\"draw_indicat"
  "or\">True</property></object><packing><property name=\"expand\">True</p"
  "roperty><property name=\"fill\">True</property><property name=\"positio"
  "n\">1</property></packing></child></object><packing><property name=\"ex"
  "pand\">True</property><property name=\"fill\">True</property><property "
  "name=\"position\">0</property></packing></child><child><object class=\""
  "GtkVBox\" id=\"vbox6\"><property name=\"visible\">True</property><prope"
  "rty name=\"can_focus\">False</property><property name=\"spacing\">6</pr"
  "operty><child><object class=\"GtkLabel\" id=\"label10\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><property name=\"xalign\">0</property><property name=\"label\" transla"
  "table=\"yes\">_Edge resistance:</property><property name=\"use_underlin"
  "e\">True</property><property name=\"selectable\">True</property><proper"
  "ty name=\"mnemonic_widget\">wrap_resistance_scale</property></object><p"
  "acking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">0</property></packing></ch"
  "ild><child><object class=\"GtkAlignment\" id=\"alignment4\"><property n"
  "ame=\"visible\">True</property><property name=\"can_focus\">False</prop"
  "erty><property name=\"left_padding\">12</property><child><object class="
  "\"GtkHBox\" id=\"hbox2\"><property name=\"visible\">True</property><pro"
  "perty name=\"can_focus\">False</property><property name=\"spacing\">12<"
  "/property><child><object class=\"GtkLabel\" id=\"label13\"><property na"
  "me=\"visible\">True</property><property name=\"can_focus\">False</prope"
  "rty><property name=\"label\" translatable=\"yes\" comments=\"Edge resis"
  "tance\">&lt;i&gt;Small&lt;/i&gt;</property><property name=\"use_markup\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">False</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkHScale\" id=\""
  "wrap_resistance_scale\"><property name=\"visible\">True</property><prop"
  "erty name=\"can_focus\">True</property><property name=\"update_policy\""
  ">discontinuous</property><property name=\"adjustment\">adjustment4</pro"
  "perty><property name=\"restrict_to_fill_level\">False</property><proper"
  "ty name=\"draw_value\">False</property></object><packing><property name"
  "=\"expand\">True</property><property name=\"fill\">True</property><prop"
  "erty name=\"position\">1</property></packing></child><child><object cla"
  "ss=\"GtkLabel\" id=\"label14\"><property name=\"visible\">True</propert"
  "y><property name=\"can_focus\">False</property><property name=\"label\""
  " translatable=\"yes\" comments=\"Edge resistance\">&lt;i&gt;Wide&lt;/i&"
  "gt;</property><property name=\"use_markup\">True</property></object><pa"
  "cking><property name=\"expand\">False</property><property name=\"fill\""
  ">False</property><property name=\"position\">2</property></packing></ch"
  "ild></object></child></object><packing><property name=\"expand\">True</"
  "property><property name=\"fill\">True</property><property name=\"positi"
  "on\">1</property></packing></child></object><packing><property name=\"e"
  "xpand\">True</property><property name=\"fill\">True</property><property"
  " name=\"position\">1</property></packing></child></object></child></obj"
  "ect></child><child type=\"label\"><object class=\"GtkLabel\" id=\"label"
  "6\"><property name=\"visible\">True</property><property name=\"can_focu"
  "s\">False</property><property name=\"label\" translatable=\"yes\">&lt;b"
  "&gt;Wrap workspaces when reaching the screen edge&lt;/b&gt;</property><"
  "property name=\"use_markup\">True</property></object></child></object><"
  "packing><property name=\"expand\">False</property><property name=\"fill"
  "\">True</property><property name=\"position\">1</property></packing></c"
  "hild><child><object class=\"GtkFrame\" id=\"frame3\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"label_xalign\">0</property><property name=\"shadow_type\""
  ">none</property><child><object class=\"GtkAlignment\" id=\"alignment5\""
  "><property name=\"visible\">True</property><property name=\"can_focus\""
  ">False</property><property name=\"border_width\">6</property><property "
  "name=\"bottom_padding\">6</property><property name=\"left_padding\">12<"
  "/property><child><object class=\"GtkHBox\" id=\"hbox6\"><property name="
  "\"visible\">True</property><property name=\"can_focus\">False</property"
  "><child><object class=\"GtkCheckButton\" id=\"box_move_check\"><propert"
  "y name=\"label\" translatable=\"yes\">When _moving</property><property "
  "name=\"use_action_appearance\">False</property><property name=\"visible"
  "\">True</property><property name=\"can_focus\">True</property><property"
  " name=\"receives_default\">False</property><property name=\"use_underli"
  "ne\">True</property><property name=\"draw_indicator\">True</property></"
  "object><packing><property name=\"expand\">True</property><property name"
  "=\"fill\">True</property><property name=\"position\">0</property></pack"
  "ing></child><child><object class=\"GtkCheckButton\" id=\"box_resize_che"
  "ck\"><property name=\"label\" translatable=\"yes\">When _resizing</prop"
  "erty><property name=\"use_action_appearance\">False</property><property"
  " name=\"visible\">True</property><property name=\"can_focus\">True</pro"
  "perty><property name=\"receives_default\">False</property><property nam"
  "e=\"use_underline\">True</property><property name=\"draw_indicator\">Tr"
  "ue</property></object><packing><property name=\"expand\">True</property"
  "><property name=\"fill\">True</property><property name=\"position\">1</"
  "property></packing></child></object></child></object></child><child typ"
  "e=\"label\"><object class=\"GtkLabel\" id=\"label7\"><property name=\"v"
  "isible\">True</property><property name=\"can_focus\">False</property><p"
  "roperty name=\"label\" translatable=\"yes\">&lt;b&gt;Hide content of wi"
  "ndows&lt;/b&gt;</property><property name=\"use_markup\">True</property>"
  "</object></child></object><packing><property name=\"expand\">False</pro"
  "perty><property name=\"fill\">True</property><property name=\"position\""
  ">2</property></packing></child><child><object class=\"GtkFrame\" id=\"f"
  "rame4\"><property name=\"visible\">True</property><property name=\"can_"
  "focus\">False</property><property name=\"label_xalign\">0</property><pr"
  "operty name=\"shadow_type\">none</property><child><object class=\"GtkAl"
  "ignment\" id=\"alignment13\"><property name=\"visible\">True</property>"
  "<property name=\"can_focus\">False</property><property name=\"top_paddi"
  "ng\">6</property><property name=\"bottom_padding\">6</property><propert"
  "y name=\"left_padding\">18</property><child><object class=\"GtkComboBox"
  "\" id=\"double_click_action_combo\"><property name=\"visible\">True</pr"
  "operty><property name=\"can_focus\">False</property><property name=\"to"
  "oltip_text\" translatable=\"yes\">The action to perform when the title-"
  "bar is double-clicked</property></object></child></object></child><chil"
  "d type=\"label\"><object class=\"GtkLabel\" id=\"label8\"><property nam"
  "e=\"visible\">True</property><property name=\"can_focus\">False</proper"
  "ty><property name=\"label\" translatable=\"yes\">&lt;b&gt;Double click "
  "_action&lt;/b&gt;</property><property name=\"use_markup\">True</propert"
  "y><property name=\"use_underline\">True</property><property name=\"mnem"
  "onic_widget\">double_click_action_combo</property></object></child></ob"
  "ject><packing><property name=\"expand\">False</property><property name="
  "\"fill\">True</property><property name=\"position\">3</property></packi"
  "ng></child></object><packing><property name=\"position\">3</property></"
  "packing></child><child type=\"tab\"><object class=\"GtkLabel\" id=\"lab"
  "el4\"><property name=\"visible\">True</property><property name=\"can_fo"
  "cus\">False</property><property name=\"label\" translatable=\"yes\">Ad_"
  "vanced</property><property name=\"use_underline\">True</property></obje"
  "ct><packing><property name=\"position\">3</property><property name=\"ta"
  "b_fill\">False</property></packing></child></object><packing><property "
  "name=\"expand\">True</property><property name=\"fill\">True</property><"
  "property name=\"position\">1</property></packing></child></object></chi"
  "ld><action-widgets><action-widget response=\"-11\">help_button</action-"
  "widget><action-widget response=\"0\">close_button</action-widget></acti"
  "on-widgets></object><object class=\"GtkSizeGroup\" id=\"sizegroup1\"><p"
  "roperty name=\"mode\">vertical</property><widgets><widget name=\"alignm"
  "ent17\"/><widget name=\"alignment18\"/></widgets></object></interface>"
};

static const unsigned xfwm4_dialog_ui_length = 48063u;

